- name: create ec2 instances
  hosts: local
  connection: local
  vars:
    aansibleserver:
    - mysql
    - backend
    - frontend
    zone: rupakalpan.shop
    
  tasks:
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9
  
  - name: create ec2 instances    
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "subnet-00a686d0e79dedb31"
      instance_type: "t3.micro"
      security_group: "sg-0201d0d466a3135e4"
      image_id: "ami-09c813fb71547fc4f"    
    loop: "{{ ansibleserver }}"
    register: nexus
  
  - name: check the result output
    ansible.builtin.debug:
      msg: "{{ nexus }}"
  
  - name: create rout53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true     
    loop: "{{nexus.results}}"
  
  - name: create rout53 records for public ip address
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true     
    loop: "{{ nexus.results }}"
    when: item.item == "frontend"