- name: create ec2 instances
  hosts: local
  connection: local
  vars:
    naws:
    - mysql
    - backend
    - frontend
    zone: rupakalpan.shop
    
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "subnet-00a686d0e79dedb31"
      instance_type: "t3.micro"
      security_group: "sg-0201d0d466a3135e4"
      image_id: "ami-09c813fb71547fc4f"    
    loop: "{{naws}}"
    register: qserver
  
  - name: check the result output
    ansible.builtin.debug:
      msg: "{{ qserver }}"
  
  - name: create rout53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true     
    loop: "{{qserver.results}}"
  
  - name: create rout53 records for public ip address
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true     
    loop: "{{qserver.results}}"
    when: qserver.results.item == "frontend"